name: Run tests

on :
  push:
    paths:
       - '**.py'
       - .github/workflows/tests.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          version: 3.11
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.1 # pin version to avoid breakage when Poetry change
      - run: poetry install --no-root
      - run: poetry run python manage.py test
